---
all:
  children:
    clickhouse:
      hosts:
        clickhouse-01:
          ansible_host: 46.21.246.39
          ansible_user: ubuntu
    vector:
      hosts:
        vector-01:
          ansible_host: 89.169.141.179
          ansible_user: ubuntu
    lighthouse:
      hosts:
        lighthouse-01:
          ansible_host: 89.169.130.210
          ansible_user: ubuntu
